spring:
  application:
    name: mall-backed
  profiles:
    active: dev,private
server:
  port: 8877
sa-token:
  # token名称 (同时也是cookie名称)
  token-name: token
  # token有效期，单位s 默认30天, -1代表永不过期
  timeout: 2592000
  # token临时有效期 (指定时间内无操作就视为token过期) 单位: 秒
  active-timeout: -1
  # 是否允许同一账号并发登录 (为true时允许一起登录, 为false时新登录挤掉旧登录)
  is-concurrent: true
  # 在多人登录同一账号时，是否共用一个token (为true时所有登录共用一个token, 为false时每次登录新建一个token)
  is-share: true
  # token风格
  token-style: uuid
  # 是否输出操作日志
  is-log: true
  # 自动续签
  auto-renew: true

oss:
  ali-yun:
    access-key-id: accessKeyId # 阿里云access key id
    access-key-secret: secret # secret
    endpoint: oss-cn-qingdao.aliyuncs.com
    bucket-name: my-community
  provider: ali_yun
sms:
  ali-yun:
    access-key-id:
    access-key-secret:
    sign-name:
    template-code:
  # 如果sms服务商是阿里云下面的provider改成aliyun
  provider: none
wx:
  miniapp:
    appid: appid
    secret: secret
    config-storage:
      http-client-type: HttpClient
      type: redistemplate
  pay:
    appId: appid
    mchId: secret #商户id
    apiV3Key: v3Key #V3密钥
    certSerialNo: cc
    privateKeyPath: cc #apiclient_key.pem证书文件的绝对路径或者以classpath:开头的类路径
    privateCertPath: cc  #apiclient_cert.pem证书文件的绝对路径或者以classpath:开头的类路径